# Generated by Django 5.1.7 on 2025-04-04 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_product_gst_alter_product_hsn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='bill_number',
            new_name='bill_no',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_gst',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.product'),
        ),
    ]
